### PR TITLE
Add typing (typescript).

### PR DESCRIPTION
**Pull request by bbaumgartl**
Would be nice since redux and reselect both have it.

### CODE REVIEW

**Comment by tswaters** [comment]
Thabks for the contribution!  I'll publish a new version to npm once I am at a computer, probably a few hours.

**Comment by bernimoses** [comment]
Nice thx 🙂

**Comment by bbaumgartl** [comment]
Nice thx 🙂

**Comment by tswaters** [comment]
Published as v1.0.2

**Pull request merged**
